-- Tactic Boss AI V101
-- No Supabase SQL migration is required.
-- V101 stores final-plan metadata inside existing JSON columns:
-- saved_tactics.input_data
-- saved_tactics.result_data
--
-- Optional verification only:
-- select column_name, data_type
-- from information_schema.columns
-- where table_name = 'saved_tactics'
--   and column_name in ('input_data', 'result_data');
